# Generated by Django 2.2.7 on 2019-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0002_auto_20191208_0807'),
        ('accounts', '0007_auto_20191230_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLat', models.FloatField()),
                ('startLon', models.FloatField()),
                ('endLat', models.FloatField()),
                ('endLon', models.FloatField()),
                ('price', models.FloatField()),
                ('distance', models.IntegerField()),
                ('starttime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
                ('Journey_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], default=1)),
                ('stat', models.IntegerField(choices=[(1, 'REQUEST'), (2, 'WAIT DRIVER RESPONSE'), (3, 'DRIVER ACCEPT'), (4, 'DRIVER ARRIVE'), (5, 'STAR TRIP'), (6, 'FINISH'), (7, 'PAID'), (9, 'REJECT')], default=1)),
                ('Categories', models.ForeignKey(blank=True, null=True, on_delete=None, to='Categories.Categories')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=None, to='accounts.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=None, to='accounts.driver')),
            ],
        ),
    ]
