# Generated by Django 2.2.7 on 2019-12-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLat', models.FloatField()),
                ('startLon', models.FloatField()),
                ('endLat', models.FloatField()),
                ('endLon', models.FloatField()),
                ('price', models.FloatField()),
                ('distance', models.IntegerField()),
                ('starttime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'REQUEST'), (2, 'DRIVER RESPONSE'), (3, 'END'), (4, 'CANCEL'), (5, 'DECLINE')], default=1)),
                ('Categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.Categories')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
