# Generated by Django 2.2.7 on 2019-12-09 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journey', '0002_auto_20191208_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='Categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='Categories.Categories'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
