# Generated by Django 2.2.7 on 2019-12-05 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2019, 12, 5, 20, 34, 3, 784881, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
