# Generated by Django 2.2.7 on 2019-12-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191209_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='log',
            new_name='lon',
        ),
    ]
