# Generated by Django 2.2.7 on 2019-12-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191230_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Driver'},
        ),
    ]
