# Generated by Django 2.2.7 on 2019-12-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassNo', models.CharField(max_length=25)),
                ('plateNo', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=90)),
                ('year', models.IntegerField()),
                ('Categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.Categories')),
            ],
        ),
    ]
