# Generated by Django 2.2.7 on 2019-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='Categories.Categories'),
        ),
    ]
