# Generated by Django 2.2.7 on 2019-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_auto_20191209_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
