# Generated by Django 2.2.7 on 2019-12-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
