# Generated by Django 2.2.7 on 2019-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expDate', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('issuePlace', models.CharField(max_length=90)),
            ],
        ),
    ]
